spring:
  datasource:
    url: jdbc:mysql://localhost:3306/woplanner
    username: newuser
    password: Faszombele444!
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
